# Generated by Django 3.0.7 on 2020-08-14 10:48

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200814_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutaddress',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None),
        ),
    ]
