# Generated by Django 3.0.7 on 2020-09-06 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200906_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutaddress',
            name='state',
            field=models.CharField(choices=[('O', 'Online'), ('C', 'Cod')], max_length=200),
        ),
    ]
