# Generated by Django 3.0.7 on 2020-09-06 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200906_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutaddress',
            name='state',
            field=models.CharField(choices=[('andhra pradesh', 'ANDHRA PRADESH'), ('telangana', 'TELANGANA')], default='telangana', max_length=200),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.CheckoutAddress'),
        ),
    ]
