# Generated by Django 3.0.7 on 2020-08-16 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200816_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='checksum',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
