# Generated by Django 3.0.7 on 2020-07-18 07:53

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200718_1247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='phone',
        ),
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='phone',
            field=phone_field.models.PhoneField(max_length=31, null=True),
        ),
    ]
