# Generated by Django 3.0.7 on 2020-07-18 12:50

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200718_1323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
        migrations.AddField(
            model_name='customer',
            name='phone',
            field=phone_field.models.PhoneField(max_length=31, null=True, unique=True),
        ),
    ]
