# Generated by Django 3.0.7 on 2020-08-29 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='images/blog-default.jpg', null=True, upload_to='images/'),
        ),
    ]
